theme = "hugo-xmin"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
publishDir = "docs"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
[params]
    footer = "&copy; [Phil Roberts](https://philbroberts.github.io/) 2020"